const RGESN_CRITERIA = [
 {
  "id": "1.1",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique a-t-il été évalué favorablement en termes d’utilité en tenant compte de ses impacts environnementaux ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Afficher dans la déclaration d’écoconception du service numérique comment a été évalué le service, par exemple dans quels objectifs de développement durable il s’inscrit, quelles sont les réponses apportées aux enjeux de limites planétaires ou autre référentiel utilisé (préciser lequel), et leur pertinence.Un service numérique valide ce critère s’il fait l’objet d’une étude visant à évaluer et justifier les impacts environnementaux et sociaux.",
  "exempleDeclaration": "Le service [à compléter] a été évalué favorablement en termes d’utilité en tenant compte de [référence : norme/standard/politique publique].En effet, le service devrait permettre de : [à détailler]"
 },
 {
  "id": "1.2",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique a-t-il défini ses cibles utilisatrices, les besoins métiers et les attentes réelles des utilisateurs-cibles ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Pour valider ce critère, le profil des cibles utilisatrices ainsi que l’analyse des besoins métiers et des attentes des utilisateurs devraient être clairement renseignés dans la déclaration d’écoconception du service numérique ainsi que les choix effectués en ce sens.",
  "exempleDeclaration": "Les cibles utilisatrices du service [à compléter] ont été identifiées en procédant à [détailler la méthodologie].Ainsi, les cibles utilisatrices du service sont [à détailler].En cohérence, le service numérique répond à leurs besoins puisque présentant les fonctionnalités suivantes : [détailler en quoi les fonctionnalités du service répondent à la cible utilisatrice]"
 },
 {
  "id": "1.3",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique a-t-il au moins un référent identifié en écoconception numérique ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Le critère est validé si un contact (nominal ou générique) est précisé dans la déclaration d’écoconception du service ou tout autre document public aisément accessible.",
  "exempleDeclaration": "Personnes référentes en écoconception numérique pour le service :• Nom(s) [à compléter]• Titre [à compléter]"
 },
 {
  "id": "1.4",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique réalise-t-il régulièrement des revues pour s’assurer du respect de sa démarche d’écoconception ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Pour valider ce critère, il convient de mettre en œuvre une revue ou autoévaluation régulière appliquant ce référentiel et d’en rendre compte dans la déclaration d’écoconception du service. Des audits de performance et des tests de charge réguliers devront également être effectués.",
  "exempleDeclaration": "Pour ce faire, des audits réguliers sont réalisés tous les [à compléter] pour améliorer en continu la performance environnementale du service."
 },
 {
  "id": "1.5",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique s’est-il fixé des objectifs en matière de réduction ou de limitation de ses propres impacts environnementaux ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Le critère est validé si l’empreinte environnementale du service a été évaluée – avec une méthodologie reconnue, si possible une ACV (multicritère) évaluant les impacts du service sur tout son cycle de vie – et si le service s’est fixé des objectifs de réduction d’impact. Ces éléments doivent faire l’objet d’un suivi régulier et être renseignés dans un document public et auditable, par exemple la déclaration d’écoconception du service.",
  "exempleDeclaration": "L’empreinte environnementale du service [à compléter] a été évaluée le [renseigner la date de l’évaluation] en suivant la méthode de quantification d'impact [à compléter]. Ainsi, les indicateurs environnementaux suivants ont pu être calculés :• Empreinte carbone [à compléter]• Consommation d’énergie : [à compléter]• Consommation en ressources abiotiques minérales/métaux [à compléter]• Consommation en eau bleue : [à compléter]"
 },
 {
  "id": "1.6",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique collecte-t-il la donnée de façon responsable et raisonnée ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Pour l’ensemble des données collectées (y compris non personnelles), justifier dans la déclaration d’écoconception du service le besoin de cette collecte au regard des cibles utilisatrices du service (critère 1.2), la limitation de leur traitement et de la durée de conservation, et documenter les outils de recueil du consentement le cas échéant. En ce qui concerne les données personnelles, un renvoi pourra être fait au registre de traitements des données personnelles tel que prévu par le RGPD.Ne pas collecter des métadonnées servant au profilage de l’utilisateur, sauf si cette collecte est essentielle aux besoins et cibles utilisatrices du service (critère 1.2) ou au fonctionnement de ce dernier, et si l’utilisateur a donné son consentement explicite et éclairé et qu’il peut désactiver cette collecte à tout moment. Le cas échéant, ces éléments devront être documentés dans la déclaration d’écoconception du service numérique.",
  "exempleDeclaration": "Le service numérique collecte des données afin de répondre aux besoins de [à compléter].Il ne comporte pas de collecte de métadonnées à des fins publicitaires / Il collecte des métadonnées à des fins publicitaires, sous réserve du consentement explicite et éclairé de l’utilisateur, puisqu’il s’agit d’une démarche essentielle pour les fonctionnalités suivantes [à compléter][insérer un renvoi vers les mentions légales si pertinent]"
 },
 {
  "id": "1.7",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique a-t-il recours à un niveau de chiffrement adapté à ses besoins ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service n’a pas recours à un mécanisme de chiffrement",
  "moyenTest": "Si le service repose sur des mécanismes de chiffrement, documenter dans la déclaration d’écoconception du service la pertinence du choix de mise en œuvre des mécanismes cryptographiques en fonction des risques de sécurité informatique du service et de la minimisation de l’empreinte environnementale associée.",
  "exempleDeclaration": "Afin d’assurer la sécurité des données du service, des mécanismes cryptographiques sont mis en place.Le choix s’est orienté vers les technologies [à compléter] après une analyse des risques de sécurité informatique du service et de l’empreinte environnementale associée, dont voici les contours publics : [à détailler]"
 },
 {
  "id": "1.8",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique a-t-il mis en place des efforts d’open source ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Le critère est validé si le code du service est publié en licence libre ou si les choix et efforts effectués en la matière sont justifiés dans la déclaration d’écoconception du service numérique.",
  "exempleDeclaration": "Le service numérique publie [tout/une partie] de son code en opensource, sous la licence [à compléter].Des efforts sont déployés pour favoriser l’ouverture et le partage des ressources du service en opensource comme le montre les actions suivantes : [à détailler]"
 },
 {
  "id": "1.9",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique a-t-il été conçu avec des technologies standard interopérables plutôt que des technologies spécifiques et fermées ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Vérifier que le service numérique est utilisable par une même interface sur l’ensemble des terminaux pertinents (par exemple : une Web App). Si le service numérique est une application native, évaluer la nécessité d’avoir choisi de développer une application native : contraintes techniques, matériel cible maîtrisé ?Le critère est validé si le service s’appuie sur des standards interopérables communs aux principaux écosystèmes (terminaux, systèmes d’exploitation, navigateurs...).",
  "exempleDeclaration": ""
 },
 {
  "id": "1.10",
  "themeNum": 1,
  "theme": "Stratégie",
  "libelle": "Le service numérique repose-t-il sur des API documentées et ouvertes pour interagir avec le matériel ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur un objet connecté ou un périphérique matériel",
  "moyenTest": "Si le service numérique repose sur l’utilisation d’un terminal, équipement, appareil, le fournisseur doit rendre disponibles les API nécessaires à l’exploitation de l’objet connecté. Les API du périphérique doivent être documentées et d’usage libre, afin qu’un programme ou pilote alternatif puisse être créé pour prolonger la durée de vie de l’objet ou du périphérique.",
  "exempleDeclaration": ""
 },
 {
  "id": "2.1",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique a-t-il défini la liste des profils de matériels que les utilisateurs vont pouvoir employer pour y accéder ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Le critère est validé si le profil des matériels supportés par le service est établi de façon à privilégier les équipements aussi anciens que possible et le profil matériel minimum est affiché dans la déclaration d’écoconception du service. Si certaines fonctionnalités requièrent une version plus récente, indiquer les versions minimales avec et sans support de ces fonctionnalités. Il convient également d’indiquer les éventuelles évolutions à venir sur la configuration matérielle minimum.",
  "exempleDeclaration": "• Processeur minimum : [à compléter]• Mémoire vive minimum :  [à compléter]• Évolution à venir sur la configuration matérielle minimum à partir de [date + 2 ans] : [à compléter]"
 },
 {
  "id": "2.2",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique est-il utilisable sur d’anciens modèles de terminaux ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "• Si le service numérique est une application native : il convient de tester les fonctionnalités critiques du service numérique sur un équipement ancien (par exemple un smartphone, une tablette ou TV connectée), c’est-à-dire mis sur le marché il y a sept ans ou plus, dans la dernière version du système d’exploitation proposé par cet équipement.• Si le service numérique fonctionne sur un navigateur web : les fonctionnalités critiques doivent fonctionner sur un PC portable – ou un autre terminal, tant que cela est cohérent avec les terminaux qui sont majoritairement utilisés par les cibles utilisatrices du service définies en suivant le critère 1.2 – équipé d’un microprocesseur mis sur le marché il y a dix ans ou plus.• Pour les autres services numériques : tester les fonctionnalités critiques du service sur un terminal (exemple : équipements connectés) mis sur le marché il y a sept ans ou plus.Sont à indiquer dans la déclaration d’écoconception du service les caractéristiques matérielles et logicielles de l’équipement ancien qui permet de faire fonctionner le service.",
  "exempleDeclaration": "• Caractéristiques matérielles et logicielles de l’équipement ancien qui permet de faire fonctionner le service : [à compléter]"
 },
 {
  "id": "2.3",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique est-il utilisable via une connexion bas débit ou hors connexion ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "L’utilisabilité du service devra être testée avec des connexions bas débit (3G en mobilité et 512 Kbit/s en fixe) ou hors connexion. Le critère est validé si le service numérique est utilisable sans connexion au réseau ou avec une connexion bas débit. Le débit minimum sera présenté dans la déclaration d’écoconception.",
  "exempleDeclaration": "• Connexion internet minimum : [à compléter]"
 },
 {
  "id": "2.4",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique est-il utilisable sur d’anciennes versions de système d’exploitation et de navigateurs web ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur un système d’exploitation ou un navigateur web",
  "moyenTest": "• Si le service numérique est une application native : tester les fonctionnalités critiques du service numérique sur les systèmes d’exploitation supportés ayant cinq ans, en prenant en compte la première date de mise à disposition en version stable.• Si le service numérique fonctionne sur un navigateur web : s’assurer que les fonctionnalités critiques fonctionnent sur les principaux navigateurs web dans une version datée d’au moins deux ans, en prenant en compte la première date de mise à disposition en version stable.La déclaration d’écoconception du service numérique devrait spécifier :• Si le service numérique est une application native : les versions minimales des systèmes d’exploitation supportés.• Si le service numérique fonctionne sur un navigateur web : lister les prérequis logiciels et les versions minimales des navigateurs web compatibles et leur année de sortie. Il est pertinent de rajouter la cause de l’incompatibilité de la version précédente, s’il est possible d’en diagnostiquer la cause.",
  "exempleDeclaration": "• Prérequis logiciels / Configuration logicielle minimum : [à compléter]• Évolutions à venir sur la configuration logicielle minimum : [à compléter]"
 },
 {
  "id": "2.5",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique s’adapte-t-il à différents types de terminaux d’affichage ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique ne propose d’interface utilisateur sur écran",
  "moyenTest": "• Le service doit adapter son mode d’affichage de manière dynamique selon la taille de l’écran (« responsive web design »).• Vérifier que les différents composants de type menus soient accessibles via tout type d’interface, y compris tactile ou non, avec ou sans souris.• S’assurer de l’affichage complet du service dans une zone de visualisation de 1 200 pixels de large.• Pour les interfaces qui ne permettent pas de faire défiler de haut en bas l’affichage, vérifier l’affichage complet du service dans une zone de visualisation de 720 pixels de hauteur.Le critère est validé si les conditions susmentionnées sont remplies. Les tests effectués sont à documenter dans la déclaration d’écoconception.",
  "exempleDeclaration": "• Le service numérique s’appuie sur un affichage dynamique [à détailler]• Type d’interface compatible : [à compléter]• Tailles d’affichage supportées par le service : [à compléter]• Détail des tests réalisés : [à compléter]"
 },
 {
  "id": "2.6",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique a-t-il été conçu avec une revue de conception et une revue de code comprenant parmi ses objectifs la réduction des impacts environnementaux de chaque fonctionnalité ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Quel est le processus de développement mis en place ? Le critère est validé si :• Une revue de conception prenant en compte l’empreinte environnementale du service a été réalisée : dès sa conception, l’équipe projet devrait pouvoir définir un arbre des conséquences du service numérique en représentant, par fonctionnalité, les impacts directs et indirects du service numérique pour que toute l’équipe valide les fonctionnalités en connaissance des impacts environnementaux potentiels.• Une revue de code visant à minimiser le coût environnemental du service a été produite en aval de la conception pour les services reposant sur du code informatique.Ces revues sont – le cas échéant – référencées dans la déclaration d’écoconception du service.",
  "exempleDeclaration": "Le service numérique [à compléter] a procédé à une revue de code et de conception pour réduire le coût environnemental du service."
 },
 {
  "id": "2.7",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique a-t-il prévu une stratégie de maintenance et de décommissionnement ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Lister les fonctionnalités, les composants et les environnements actifs, en précisant leur état d'utilisation. Le critère est validé si une stratégie de maintenance et de décommissionnement est définie pour le service incluant des dates de rappel pour les éléments non utilisés et les actions prévues pour optimiser la seconde vie ou fin de vie des ressources libérées en cas de décommissionnement. Les résultats doivent être documentés dans la déclaration d’écoconception. En cas de fin de vie de tout ou partie du service, la gestion des données non personnelles et des équipements utilisés pour leur service devra être planifiée, de manière à diminuer les impacts environnementaux associés.",
  "exempleDeclaration": "Les fonctionnalités du service sont adaptées de façon dynamique dans le cadre de la politique de maintenance et de décommissionnement mis en œuvre pour assurer l’adéquation entre ces fonctionnalités et les besoins utilisateurs.[à détailler]"
 },
 {
  "id": "2.8",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique impose-t-il à ses fournisseurs de garantir une démarche de réduction de leurs impacts environnementaux ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur l’appel à des fournisseurs extérieurs",
  "moyenTest": "Le critère est validé si les caractéristiques environnementales des fournisseurs pour la conception du service numérique sont prises en compte dans la politique d’achat ou de partenariat du service, en vue des impacts environnementaux associés et documentés dans la déclaration d’écoconception.",
  "exempleDeclaration": "En cohérence avec le Guide pratique pour des achats numériques responsables, il a été demandé aux fournisseurs à qui il est fait appel pour l’opération du service de respecter les dispositions suivantes [à compléter]"
 },
 {
  "id": "2.9",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique a-t-il pris en compte les impacts environnementaux des composants d’interface prêts à l’emploi utilisés ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur des composants d’interface prêts à l’emploi",
  "moyenTest": "Le critère est validé si la majorité des composants d’interfaces utilisés par le service sont estimés performants écologiquement, en prenant notamment en compte les critères susmentionnés lorsque applicables à la fonctionnalité visée. Les choix effectués et la minimisation de l’empreinte environnementale des composants devrait également être documentée dans la déclaration d’écoconception.",
  "exempleDeclaration": "Le service numérique a recours à des composants prêts à l’emploi pour les fonctionnalités suivantes [à compléter avec la description des composants et des fonctionnalités visés].Le choix de ces composants a été effectué afin de minimiser leur l’empreinte environnementale, comme l’atteste les éléments suivants : [à compléter]"
 },
 {
  "id": "2.10",
  "themeNum": 2,
  "theme": "Spécifications",
  "libelle": "Le service numérique a-t-il pris en compte les impacts environnementaux des services tiers utilisés lors de leur sélection ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur des services tiers",
  "moyenTest": "Vérifier si les services tiers sur lesquels le service numérique repose valident les critères suivants :• Pour tous les services tiers fournis, validation des critères 1.4 et 1.5• Si le service tiers analysé est une vidéo, validation des critères 4.4, 4.11, 4.12, 4.15, 5.3, 5.4 et 5.5• Si le service tiers analysé est un réseau social, validation des critères 4.1, 4.6, 4.9, 4.12, 4.13 et 4.15• Si le service tiers analysé est un générateur d’image, validation des critères 4.6, 4.11, 4.12, 4.13 et 4.15Les services tiers utilisés sont à lister, en renseignant leur avancement au regard de ces critères (si applicables), dans la déclaration d’écoconception.",
  "exempleDeclaration": "Le service numérique repose sur les services tiers suivants [à compléter].D’après les informations [fournies par la société XX] [accessibles publiquement au lien *renvoi vers page dédiée*], le service tiers [à compléter] respecte les critères d’écoconception suivants : [à compléter]"
 },
 {
  "id": "3.1",
  "themeNum": 3,
  "theme": "Architecture",
  "libelle": "Le service numérique repose-t-il sur une architecture, des ressources ou des composants conçus pour réduire leurs propres impacts environnementaux ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service ne repose pas sur des composants",
  "moyenTest": "Le critère est validé si le choix de frameworks et composants de l’architecture a été fait en prenant en compte leur empreinte environnementale et l’écoconception, et qu’il est documenté dans la déclaration d’écoconception du service.",
  "exempleDeclaration": "Le développement du backend et frontend du service numérique repose sur le(s) framework [à compléter].Ces frameworks s’inscrivent dans la droite ligne de la démarche d’écoconception du service, comme le montre les éléments suivants : [à compléter].Les composants de l’architecture, internes [à compléter] et externes [à compléter] respectent également les principes d’écoconception que sont [à compléter]."
 },
 {
  "id": "3.2",
  "themeNum": 3,
  "theme": "Architecture",
  "libelle": "Le service numérique fonctionne-t-il sur une architecture pouvant adapter la quantité de ressources utilisées à la consommation du service ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service ne repose pas sur des ressources serveurs",
  "moyenTest": "Le service numérique fonctionne sur une architecture qui peut adapter les ressources allouées à la demande. Démontrer dans la déclaration d’écoconception l’adaptation de la consommation en ressources de l’architecture en fonction des besoins du service.",
  "exempleDeclaration": "Tests effectués démontrant l’adaptation de la consommation en ressource de l’architecture en fonction des besoins du service : [à compléter]"
 },
 {
  "id": "3.3",
  "themeNum": 3,
  "theme": "Architecture",
  "libelle": "Le service numérique est-il en mesure de supporter l’évolution technique des protocoles ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique n’utilise pas de connexion réseau internet",
  "moyenTest": "Vérifier la mise en œuvre en s’assurant :• Que les différents composants du service numérique fonctionnent bien :   ◦ En IPv6 et ne font appel à aucun service tiers IPv4-only ;   ◦ En HTTPS et non en HTTP.• Que la dernière version de TLS (au moment de la rédaction de ce référentiel : TLS v1.3) est bien supportée.• De l’adéquation du protocole utilisé par rapport au contenu transféré en tenant compte de son empreinte environnementale.Le critère est validé si le choix des protocoles nécessaires au fonctionnement du service en assure sa pérennité, en respectant, selon ses fonctionnalités, les conditions susmentionnées. Documenter les protocoles utilisés dans la déclaration d’écoconception.",
  "exempleDeclaration": "Afin de prévenir les risques d’obsolescence et de limiter le besoin en mise à jour ou modernisation, le service numérique repose sur des protocoles pérennes et adaptés à ses fonctionnalités. En particulier :• Le service numérique est accessible en IPV6 (et en IPV4)• Le service numérique repose sur le protocole HTTPS• La version de TLS utilisée doit prendre en charge la version la plus récente, c’est-à-dire [à compléter - à l’heure de rédaction de ce document, il s’agit de : TLS v1.3][etc]"
 },
 {
  "id": "3.4",
  "themeNum": 3,
  "theme": "Architecture",
  "libelle": "Le service numérique garantit-il la mise à disposition de mises à jour correctives pendant toute la durée de vie prévue des équipements et des logiciels liés au service ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A pour les services numériques qui ne sont pas commercialisés avec un terminal associé",
  "moyenTest": "Pour valider ce critère, indiquer la durée de maintenance du service dans la déclaration d’écoconception et vérifier que les mises à jour sont effectivement disponibles tout au long de la durée de vie des équipements associés.",
  "exempleDeclaration": "La politique de mises à jour du service numérique [à compléter] intègre également des principes d’écoconception afin de prévenir tout risque d’obsolescence logicielle et de limiter les mises à jour aux stricts besoins du service. Les actions suivantes sont en particulier mises en place : [exemples]• Le service numérique commercialisé avec le terminal [à compléter] sera mis à jour pendant toute la durée de vie du produit matériel, estimée à [à compléter]• Les mises à jour évolutives non nécessaire à la conformité du service [ou du terminal associé] sont proposées indépendamment des mises à jour essentielles, et de façon transparente. Celles-ci n’ont pas d’incidences négatives sur le fonctionnement du service. [si pertinent] Le service propose également une version « Long Term support ».• Le service numérique propose comme principaux types de mises à jour : [à compléter]. Il favorise ainsi les mises à jour incrémentielles / la séparation du code binaire."
 },
 {
  "id": "3.5",
  "themeNum": 3,
  "theme": "Architecture",
  "libelle": "Le service numérique propose-t-il d’installer des mises à jour correctives indépendamment des mises à jour évolutives de façon transparente ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne propose pas de mises à jour évolutives (non essentielles)",
  "moyenTest": "Pour valider ce critère :• Indiquer, dans la description des mises à jour d’une application (changelog ou journal des modifications), s’il s’agit d’une mise à jour de sécurité/maintenance (« corrective ») ou s’il s’agit d’une mise à jour évolutive ajoutant des fonctionnalités.• S’assurer que les mises à jour évolutives non essentielles à la conformité du service n’empêchent pas le service de fonctionner pendant toute la durée de maintenance des systèmes d’exploitation supportés.• Garantir, lorsque cela est possible, la possibilité d’installer de façon dissociée les mises à jour essentielles à la conformité et à la sécurité du service numérique ou du terminal de l’utilisateur aux mises à jour évolutives non nécessaires à la conformité du bien.• Si possible, vérifier la présence d'une stratégie de gestion des versions du service visant à l’optimisation des mises à jour à effectuer, avec par exemple la fourniture de versions du service « Long-term support ».",
  "exempleDeclaration": ""
 },
 {
  "id": "3.6",
  "themeNum": 3,
  "theme": "Architecture",
  "libelle": "Le service numérique propose-t-il les mises à jour incrémentielles, afin de ne pas remplacer tout le code à chaque mise à jour ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne propose pas de mise à jour",
  "moyenTest": "Il faut utiliser, lorsque cela est possible, un mécanisme de mise à jour qui ne nécessite pas de remplacer tout le code du programme à chaque mise à jour. Le cas échéant, il est possible de proposer une mise à jour complète du code du programme pour les fonctionnalités de « réinitialisation » ou « d’autoréparation ».Le critère est validé si les mises à jour incrémentielles sont favorisées pour le service numérique, en dehors des fonctionnalités de « réinitialisation » et « d’autoréparation ».",
  "exempleDeclaration": ""
 },
 {
  "id": "3.7",
  "themeNum": 3,
  "theme": "Architecture",
  "libelle": "Le service numérique optimise-t-il la sollicitation des environnements de développement, de préproduction ou de test en fonction de ses besoins ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur l’utilisation de serveur",
  "moyenTest": "Le critère est validé si le service s’appuie sur des environnements de développement / préproduction / tests mutualisés, ou bien si ces environnements sont désactivés sur les plages horaires où ils sont inutilisés.Indiquer dans la déclaration d’écoconception du service numérique les choix réalisés pour limiter les ressources utilisées par les environnements de développement, de préproduction ou de test.",
  "exempleDeclaration": "Les environnements de développement, de préproduction ou de test sont désactivés la nuit, sur les plages horaires où ils sont inutilisés / Le service numérique utilise des environnements de développement, de préproduction ou de test mutualisés.[à détailler]"
 },
 {
  "id": "4.1",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique comporte-t-il uniquement des animations, vidéos et sons dont la lecture automatique est désactivée ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Le critère est validé si le service ne repose pas sur une fonctionnalité de lecture automatique par défaut et incontrôlée, limite le recours à des animations visuelles, clignotements ou défilements automatiques non contrôlables, en suivant les conditions du critère.",
  "exempleDeclaration": ""
 },
 {
  "id": "4.2",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique affiche-t-il uniquement des contenus sans défilement infini ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique ne comporte pas d’interaction homme-machine (IHM)",
  "moyenTest": "Le critère est validé si le design du service numérique repose sur un chargement à la demande du contenu proportionné au contexte d’utilisation (notamment la mise en place d’un bouton « Voir plus » pour continuer la navigation ou une pagination), ou peut s’afficher en entier sur un écran.",
  "exempleDeclaration": ""
 },
 {
  "id": "4.3",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique optimise-t-il le parcours de navigation pour chaque fonctionnalité principale ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service ne repose pas sur un parcours de navigation",
  "moyenTest": "Le critère est validé si (conditions cumulatives) :• Les parcours de navigation sont optimisés et recentrés autour des fonctionnalités essentielles d’après les outils UX et les statistiques d’usages effectuées ;• Des indicateurs techniques pour les parcours identifiés ont été ou sont en cours de mise en place pour assurer l’optimisation dans le temps du parcours de navigation, à la lumière des retours récoltés.",
  "exempleDeclaration": ""
 },
 {
  "id": "4.4",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique permet-il à l’utilisateur de décider de l’activation d’un service tiers ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service ne repose pas sur un service tiers",
  "moyenTest": "Le critère est validé si l’activation des services tiers intégrés au service numérique est conditionnée au consentement clair et explicite de l’utilisateur, du point de vue de la protection des données lorsque applicable, avec également une information spécifique sur le possible coût environnemental.",
  "exempleDeclaration": ""
 },
 {
  "id": "4.5",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique utilise-t-il majoritairement des composants fonctionnels natifs du système d’exploitation, du navigateur ou du langage utilisé ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Le critère est validé si le service favorise le recours à des composants fonctionnels natifs lorsque cela est possible.De plus, dans l’éventualité du recours à des composants non natifs, il convient d’évaluer la nécessité d’utiliser ces composants (contraintes techniques par exemple) et, le cas échéant, de documenter dans la déclaration d’écoconception les raisons de les utiliser. Leur recours devra être régulièrement suivi en vérifiant le contenu des ressources chargées et leur utilisation effective.",
  "exempleDeclaration": "L’interface du service numérique s’appuie majoritairement sur des composants fonctionnels.L’utilisation des composants non natifs est justifiée au regard de [à compléter]"
 },
 {
  "id": "4.6",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique utilise-t-il uniquement du contenu vidéo, audio et animé porteur d’informations ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Le critère est validé si le service ne contient pas de contenu vidéo, audio ou d’animation à but purement décoratif, c’est-à-dire ne concernant pas les fonctions critiques du service. Dans la déclaration d’écoconception du service, il faudra documenter le motif d’utilisation des contenus vidéo, animés et audio afin de démontrer qu’ils servent les fonctions critiques du service et/ou apportent de l’information à l’utilisateur.",
  "exempleDeclaration": "Le service numérique n’intègre pas de contenu vidéo, audio et animé à titre purement décoratif.[à détailler si pertinent]"
 },
 {
  "id": "4.7",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique opte-t-il pour les choix les plus sobres entre le texte, l’image, l’audio ou la vidéo, selon les besoins utilisateurs ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Le critère est validé si le service n’utilise pas de contenu vidéo, audio ou animé, ou si le recours à la vidéo, à l’audio ou à l’animation a été décidé en optant pour le choix de la solution la plus sobre disponible, au regard des besoins et des fonctionnalités essentiels du service. Les choix effectués sont à justifier dans un document public (par exemple, dans la déclaration d’écoconception). La justification prendra en compte les besoins des cibles utilisatrices (voir le critère 1.2.) et à l’impact environnemental du contenu audiovisuel choisi.",
  "exempleDeclaration": "En cohérence avec les cibles utilisatrices identifiées [si besoin, renvoyer à la section dédiée de la déclaration] et l’impact environnemental différencié des contenus audiovisuels, les choix suivants de recours au texte, à l’image, l’audio ou la vidéo ont été effectués : [à détailler]"
 },
 {
  "id": "4.8",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique limite-t-il le nombre des polices de caractères téléchargées ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne comporte pas texte",
  "moyenTest": "Le critère est validé si les polices téléchargées pour le service respectent au moins l’une de ces conditions :• Le nombre de polices téléchargées est limité à deux (avec au maximum quatre variantes au total) par page ou « unité d’affichage » (si la pagination n’est pas utilisée pour le service) ;• La taille des polices téléchargées ne dépasse pas 400 Ko par page ou « unité d’affichage ».",
  "exempleDeclaration": ""
 },
 {
  "id": "4.9",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique limite-t-il les requêtes serveur lors de la saisie utilisateur ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne comporte pas d’IHM",
  "moyenTest": "Pour valider le critère, s’assurer que le service ne propose pas d’autocomplétion ; dans le cas contraire, vérifier que l’autocomplétion est justifiée du point de vue de l’utilisateur et contrôler périodiquement que l’autocomplétion attend un délai d’au moins 500 ms avant de s’activer et au moins 3 caractères saisis. L’interface utilisateur permet de désactiver l’autocomplétion.",
  "exempleDeclaration": ""
 },
 {
  "id": "4.10",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique informe-t-il l’utilisateur du format de saisie attendu, en évitant les requêtes serveur inutiles pour la soumission d’un formulaire ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur un formulaire",
  "moyenTest": "Le critère est validé si l’utilisateur est informé des formats de saisie attendus avant la soumission du formulaire. Les saisies et les formats de données obligatoires du service devront également être validés d’abord côté client avant la soumission du formulaire.",
  "exempleDeclaration": ""
 },
 {
  "id": "4.11",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique informe-t-il l’utilisateur, avant le transfert, des poids et formats de fichier attendus ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur un transfert de fichier client/serveur dans le cadre d’un formulaire",
  "moyenTest": "Le critère est validé si :• Fichiers téléchargés : les informations sur les poids et formats de fichier attendus pour le service sont correctement affichées à l'utilisateur avant le transfert, au minimum pour les fichiers de plus de 10 Mo.• Fichiers téléversés ou upload : des limitations de poids et de formats de fichiers sont mises en œuvre et sont affichées clairement pour l’utilisateur du service numérique (hors situation spécifique où de telles limitations nuiraient à l’utilisation du service).",
  "exempleDeclaration": ""
 },
 {
  "id": "4.12",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique indique-t-il à l’utilisateur que l’utilisation d’une fonctionnalité a des impacts environnementaux importants ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique ne comporte pas d’IHM",
  "moyenTest": "Le critère est validé si le service ne comprend pas de fonctionnalités ayant un impact environnemental significatif ou si les informations relatives aux impacts environnementaux sont correctement affichées pour les fonctionnalités spécifiques identifiées comme ayant des conséquences significatives en termes de consommation de bande passante, énergétique ou de ressources informatiques. L’ajout d’une équivalence avec des indicateurs environnementaux dans l’affichage à l’utilisateur n’est pas obligatoire pour valider le critère.",
  "exempleDeclaration": "L’évaluation environnementale du service met en lumière ces fonctionnalités comme ayant un impact environnemental le plus significatif : [à compléter]Ainsi, lorsque l’utilisateur demande l’accès à ces fonctionnalités par son interface, il est informé de l’impact environnemental de cette fonctionnalité aux moyens de [à compléter], qui met les indicateurs environnementaux suivants : [à compléter]"
 },
 {
  "id": "4.13",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique limite-t-il le recours aux notifications, tout en laissant la possibilité à l’utilisateur de les désactiver ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique ne comporte pas d’IHM",
  "moyenTest": "Le critère est validé si le service numérique :• Ne propose pas de notification ou propose par défaut un nombre de notifications limité (un seuil inférieur à cinq par jour devrait être visé) ;• Donne à l’utilisateur la possibilité de désactiver et de réduire, via son interface, les notifications proposées par le service de façon simple et rapide (par exemple, un bouton directement visible sur l’interface utilisateur). Les possibilités de suppression ou de réduction des notifications doivent être mises en évidence dans le service numérique.",
  "exempleDeclaration": "En matière de notifications, le service par défaut prévoit [à compléter avec la fréquence et nombre de notifications]L’utilisateur a bien la possibilité de désactiver ou de réduire les notifications du service : [à détailler]"
 },
 {
  "id": "4.14",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique évite-t-il le recours à des procédés manipulatoires dans son interface utilisateur ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique ne comporte pas d’IHM",
  "moyenTest": "Ne pas inclure de dark patterns dans le design du service et effectuer une évaluation régulière de l'interface utilisateur pour détecter et prévenir leur présence. Cette évaluation doit prendre en compte les travaux de la Commission européenne (y compris les lignes directrices publiées en application de l’article 25 du règlement 2022/2065). Le critère est validé si l'interface utilisateur ne contient pas de dark patterns.",
  "exempleDeclaration": ""
 },
 {
  "id": "4.15",
  "themeNum": 4,
  "theme": "UX / UI",
  "libelle": "Le service numérique fournit-il à l’utilisateur un moyen de contrôle sur ses usages afin de suivre et de réduire les impacts environnementaux associés ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique ne comporte pas d’IHM",
  "moyenTest": "Le critère est validé si le service numérique respecte les conditions cumulatives suivantes :• Le service affiche sur son interface une information à destination des utilisateurs sur l’empreinte environnementale de l’usage du service.• Le service numérique propose un mode d’affichage et d’usage sobre, par défaut ou dont l’activation est laissée à la discrétion de l’utilisateur, pour diminuer l’empreinte environnementale associée à son usage. L’utilisateur pourra avoir accès à une information détaillant les paramètres de ce mode « sobriété énergétique » et les gains environnementaux associés.Documenter les actions mises en place dans la déclaration d’écoconception, en particulier l’information environnementale délivrée à l’utilisateur et le paramétrage du mode de « sobriété énergétique », y compris les gains environnementaux associés.",
  "exempleDeclaration": "Le service numérique permet également à l’utilisateur de connaître l’impact environnemental de son usage, en lien avec les recommandations [de la recommandation de l’Arcom quant à l'information des consommateurs par les services de télévision, les services de médias audiovisuels à la demande et les services de plateforme de partage de vidéos / du « Référentiel par catégorie de produit » de l’ADEME / autre référentiel reconnu par la puissance publique].L’utilisateur a accès à un mode [d’usage/d’affichage] de type « sobriété énergétique » [par défaut / via son interface utilisateur principale] qui comprend les caractéristiques suivantes [à détailler]."
 },
 {
  "id": "5.1",
  "themeNum": 5,
  "theme": "Contenus",
  "libelle": "Le service numérique utilise-t-il un format de fichier adapté au contenu et au contexte de visualisation de chaque image ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique n’utilise pas d’image matricielle (ou images bitmap)",
  "moyenTest": "Vérifier périodiquement que les images matricielles ne sont plus dans les formats JPEG, PNG ou GIF. Utiliser WebP, AVIF, JPEG XL ou un format d’image plus performant pour les images matricielles. Le critère est validé si plus de 75 % des images matricielles utilisées pour le service numérique sont dans un format efficace (WebP, AVIF, JPEG XL ou un format d’image plus performant).",
  "exempleDeclaration": ""
 },
 {
  "id": "5.2",
  "themeNum": 5,
  "theme": "Contenus",
  "libelle": "Le service numérique propose-t-il des images dont le niveau de compression est adapté au contenu et au contexte de visualisation ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique n’utilise pas d’image matricielle (ou images bitmap)",
  "moyenTest": "Évaluer la qualité et le poids des images matricielles affichées sur différents types de terminaux.Pour le mode de compression avec perte, documenter dans la déclaration d’écoconception la politique de paramétrage de la qualité lors de la génération ou conversion des images.",
  "exempleDeclaration": "• Présence de résolutions multiples : [à compléter]• Politique de paramétrage de la qualité, lors de l’enregistrement des images : [à compléter]"
 },
 {
  "id": "5.3",
  "themeNum": 5,
  "theme": "Contenus",
  "libelle": "Le service numérique utilise-t-il, pour chaque vidéo, une définition adaptée au contenu et au contexte de visualisation ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A pour la diffusion de vidéos par multicast/broadcast",
  "moyenTest": "Tester, y compris périodiquement, la lecture des vidéos sur différents terminaux afin de vérifier que ces vidéos en mode « qualité standard » et « sobriété énergétique » ont un format adapté à ces terminaux.Pour valider ce critère, documenter dans la déclaration d’écoconception les définitions proposées selon les types de terminaux, l’action du mode « sobriété énergétique », son emplacement et sa capacité à mémoriser le choix de l’utilisateur.",
  "exempleDeclaration": "• Définitions proposées selon les types de terminaux : [à compléter]• Description mode « économie de données » / « sobriété énergétique » : [à compléter]"
 },
 {
  "id": "5.4",
  "themeNum": 5,
  "theme": "Contenus",
  "libelle": "Le service numérique propose-t-il des vidéos dont le mode de compression est efficace et adapté au contenu et au contexte de visualisation ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique ne propose pas de vidéos",
  "moyenTest": "Le critère est validé si le service remplit les conditions suivantes :• Les vidéos sont encodées avec un débit variable, quel que soit le codec vidéo utilisé. Ce mode d’encodage peut dans certains cas être associé à un plafond pour le débit maximal afin d’assurer que les contenus plus complexes restent lisibles avec une connexion internet à bas débit.• Les vidéos disponibles sur le service numérique ont une définition inférieure à 720p ou sont proposées avec un codec vidéo efficace, à date AV1, VP9 ou HEVC.• Le ou les codecs utilisés sont accélérés matériellement par la majorité du parc des terminaux.• Sont documentés dans la déclaration d’écoconception du service numérique le(s) codec(s) vidéo et audio utilisé(s) pour chaque définition vidéo, le type d’encodage vidéo : débit fixe, variable, variable avec débit maximum/présence de HDR, et le type d’encodage audio : débit, nombre de canaux.",
  "exempleDeclaration": "• Codec(s) vidéo et audio utilisé(s) pour chaque définition vidéo : [à compléter]• Type d’encodage vidéo : [à compléter]• Type d’encodage audio : [à compléter]"
 },
 {
  "id": "5.5",
  "themeNum": 5,
  "theme": "Contenus",
  "libelle": "Le service numérique propose-t-il un mode « écoute seule » pour ses vidéos ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique ne propose pas de contenu vidéo avec piste audio",
  "moyenTest": "Le critère est validé si :• Le service propose un mode « écoute seule » sur les vidéos, activable à la demande de l’utilisateur et qui s’enclenche lorsqu’il peut être détecté que la vidéo n’est pas affichée sur le terminal (par exemple : changement d’onglet dans un navigateur ou d’application sur un terminal, fermeture d’écran, etc.). Dans l’éventualité où les vidéos du service sont déjà hébergées par un service tiers qui ne propose pas ce mode « écoute seule », il est possible de valider le critère en proposant un enregistrement « écoute seule » sous chaque vidéo (sans préchargement de la vidéo associée).• Sont documentés dans la déclaration d’écoconception du service numérique l’emplacement et le fonctionnement du mode « écoute seule ».",
  "exempleDeclaration": "• Emplacement et fonctionnement du mode « écoute seule » : [à compléter]"
 },
 {
  "id": "5.6",
  "themeNum": 5,
  "theme": "Contenus",
  "libelle": "Le service numérique propose-t-il des contenus audios dont le mode de compression est adapté au contenu et au contexte d’écoute ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne propose pas de contenu audio",
  "moyenTest": "Le critère est validé si le service remplit les conditions suivantes :• Les contenus audio disponibles sur le service numérique sont proposés avec un codec audio efficace, à date Opus, AAC, HE-AAC, HE-AAC v2, HD-AAC, Dolby E-AC-3 ou Dolby AC-4 (un codec non efficace peut être proposé en fallback, à condition qu’un codec plus performant soit proposé aux terminaux compatibles).• Le(s) codec(s) audio utilisé(s) et le type d’encodage audio (débit, nombre de canaux) sont documentés dans la déclaration d’écoconception du service numérique.",
  "exempleDeclaration": "• Codec(s) audio utilisé(s) : [à compléter]• Type d’encodage audio : débit, nombre de canaux : [à compléter]"
 },
 {
  "id": "5.7",
  "themeNum": 5,
  "theme": "Contenus",
  "libelle": "Le service numérique utilise-t-il un format de fichier adapté au contenu et au contexte d’utilisation pour chaque document ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur l’utilisation de fichiers",
  "moyenTest": "Le critère est validé si les documents utilisés pour l’opération du service numérique sont compressés de façon à réduire leur poids et à s’adapter au contexte de visualisation, d’utilisation, et à leur contenu. La stratégie de compression des documents doit être documentée et auditable par un tiers, par exemple en étant détaillée dans la déclaration d’écoconception du service numérique.",
  "exempleDeclaration": "• Stratégie de compression des documents : [à compléter]"
 },
 {
  "id": "5.8",
  "themeNum": 5,
  "theme": "Contenus",
  "libelle": "Le service numérique a-t-il une stratégie d’archivage et de suppression, automatique ou manuelle, des contenus obsolètes ou périmés ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service ne gère pas de contenu",
  "moyenTest": "Pour valider ce critère, vérifier l’existence d’une stratégie d’archivage et de suppression clairement définie, l’existence de mécanismes automatiques et de processus manuels pour les contenus dont le traitement requiert une intervention humaine. Le suivi de cette stratégie pourra être réalisé en évaluant régulièrement le taux d’occupation des bases de données et des serveurs physiques.",
  "exempleDeclaration": ""
 },
 {
  "id": "6.1",
  "themeNum": 6,
  "theme": "Frontend",
  "libelle": "Le service numérique s’astreint-il à un poids maximum et une limite de requête par écran ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur l’utilisation d’un écran",
  "moyenTest": "Afficher dans la déclaration d’écoconception :• Le poids maximum par écran défini et proportionné, et respecter cette limite ;• Le nombre de requêtes maximum par écran défini, en précisant si la limitation du nombre de requêtes porte sur le seul chargement de la page web ou également sur son fonctionnement.",
  "exempleDeclaration": "• Poids des ressources maximum astreint par écran : [à compléter]• Nombre de requêtes serveurs maximum astreinte par écran : [à compléter]"
 },
 {
  "id": "6.2",
  "themeNum": 6,
  "theme": "Frontend",
  "libelle": "Le service numérique utilise-t-il des mécanismes de mise en cache pour la totalité des contenus transférés dont il a le contrôle ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur l’utilisation d’un serveur",
  "moyenTest": "Pour valider ce critère, un mécanisme de cache côté utilisateur est mis en place, quand la solution est pertinente. Expliciter dans la déclaration d’écoconception du service la stratégie de cache frontend, y compris son optimisation au regard du type de contenu, du contexte d’application et des scénarios d’usage.",
  "exempleDeclaration": "Le service numérique a mis en place une stratégie de cache, optimisée au regard du type de contenu, du contexte d’application et des scénarios d’usage.En voici les principaux contours côté terminal [à compléter]."
 },
 {
  "id": "6.3",
  "themeNum": 6,
  "theme": "Frontend",
  "libelle": "Le service numérique a-t-il mis en place des techniques de compression pour les ressources transférées dont il a le contrôle ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique n’utilise pas de connexion réseau internet",
  "moyenTest": "Le critère est validé si les requêtes du service numérique utilisent un mécanisme de compression des données au niveau du frontend. Pour le protocole HTTP et la compression HTML, les mécanismes de compression Brotli ou GZIP sont conseillés.",
  "exempleDeclaration": ""
 },
 {
  "id": "6.4",
  "themeNum": 6,
  "theme": "Frontend",
  "libelle": "Le service numérique affiche-t-il majoritairement des images dont les dimensions d’origine correspondent aux dimensions du contexte d’affichage ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique n’inclut pas de graphiques et/ou médias",
  "moyenTest": "Pour être valider ce critère, les images doivent entrer dans une des trois catégories suivantes :• Images vectorielles ;• Images matricielles, affichées dans leur taille d’origine (pas de redimensionnement) ;• Dans le cas d'images fluides (l'image occupe un pourcentage de la largeur du parent), plusieurs variantes d'images existent avec des définitions différentes, et la meilleure est proposée à l'écran, en fonction du contexte d’affichage.Si le service numérique permet à un contributeur d’ajouter des images, un redimensionnement doit être réalisé côté serveur pour les images qui dépasseraient une certaine taille ou définition d’image.",
  "exempleDeclaration": ""
 },
 {
  "id": "6.5",
  "themeNum": 6,
  "theme": "Frontend",
  "libelle": "Le service numérique évite-t-il de déclencher le chargement de ressources et de contenus inutilisés pour chaque fonctionnalité ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique n’utilise pas d’interface graphique",
  "moyenTest": "Vérifier le contenu des ressources chargées et leur utilisation effective en s'assurant qu'elles correspondent aux fonctionnalités effectivement utilisées : pour valider ce critère, il ne doit pas y avoir de ressources chargées inutilement.",
  "exempleDeclaration": ""
 },
 {
  "id": "6.6",
  "themeNum": 6,
  "theme": "Frontend",
  "libelle": "Le service numérique restreint-il l’usage des capteurs des terminaux utilisateurs au besoin du service ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique fonctionne sans l’usage de capteurs des terminaux des utilisateurs",
  "moyenTest": "Le critère est validé si un mécanisme d’alerte et de consentement s’enclenche pour tout déclenchement de capteur du terminal.",
  "exempleDeclaration": ""
 },
 {
  "id": "6.7",
  "themeNum": 6,
  "theme": "Frontend",
  "libelle": "Le service numérique héberge-t-il toutes les ressources statiques transférées dont il est l’émetteur sur un même domaine ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique n’utilise pas le protocole HTTP",
  "moyenTest": "Le critère est validé si (conditions cumulatives) :• L’ensemble de ses ressources prennent en charge HTTP/2 ou HTTP/3 ;• Les ressources statiques, hors services tiers, sont transférées via un seul nom de domaine à un instant « t ».",
  "exempleDeclaration": ""
 },
 {
  "id": "7.1",
  "themeNum": 7,
  "theme": "Backend",
  "libelle": "Le service numérique a-t-il recours à un système de cache serveur pour les données les plus utilisées ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service repose sur des requêtes ne pouvant être mises en cache ou s’il ne s’appuie pas sur la réponse d’un serveur",
  "moyenTest": "Pour valider ce critère :• Vérifier la configuration des systèmes de cache serveurs utilisés et s’assurer que les ressources les plus utilisées sont mises en cache ;• Examiner la présence et les règles d’expiration qui doivent être correctement paramétrées en fonction des caractéristiques de chaque fonctionnalité ;• S’assurer de la présence d’un mécanisme de rafraîchissement du cache.• Expliquer la stratégie de gestion de cache côté serveur dans la déclaration d’écoconception du service.",
  "exempleDeclaration": "Le service numérique a mis en place une stratégie de cache, optimisée au regard du type de contenu, du contexte d’application et des scénarios d’usage.En voici les principaux contours côté serveurs [à compléter]."
 },
 {
  "id": "7.2",
  "themeNum": 7,
  "theme": "Backend",
  "libelle": "Le service numérique met-il en place des durées de conservation sur les données et documents en vue de leur suppression ou archivage passé ce délai ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique ne repose pas sur l’utilisation d’un serveur",
  "moyenTest": "Pour valider ce critère, définir des dates d’expiration pour les informations obsolètes et mettre en place un mécanisme d’archivage ou de suppression des données dépassant la durée de conservation définie. Un suivi de l’évolution du poids des fichiers stockés et des bases de données.",
  "exempleDeclaration": ""
 },
 {
  "id": "7.3",
  "themeNum": 7,
  "theme": "Backend",
  "libelle": "Le service numérique informe-t-il l’utilisateur d’un traitement en cours en arrière-plan ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique ne fait pas de traitement en arrière-plan",
  "moyenTest": "Réaliser des tests fonctionnels permettant de vérifier que lorsqu'une action est en cours de traitement, le bouton ou l'élément déclencheur est désactivé et qu'un indicateur visuel ou un message d'attente est présent pour informer l'utilisateur.",
  "exempleDeclaration": ""
 },
 {
  "id": "7.4",
  "themeNum": 7,
  "theme": "Backend",
  "libelle": "Le service numérique s’appuie-t-il sur un mécanisme de consensus qui minimise sa consommation de ressources ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service ne repose pas sur un mécanisme de consensus",
  "moyenTest": "Si le service repose sur une blockchain ayant recours à la preuve de travail ou à un algorithme de consensus reposant sur le minage et, de façon générale, associée à une consommation énergétique et en ressources élevée, le critère n’est pas validé.Le choix de la blockchain et la pertinence de l’algorithme de consensus choisi au regard des enjeux environnementaux devront être documentés dans la déclaration d’écoconception.",
  "exempleDeclaration": "Le service repose sur une blockchain qui utilise l’algorithme de consensus suivant : [à compléter].Le choix de la technologie utilisée minimise l’impact environnemental du service puisque [à détailler]."
 },
 {
  "id": "8.1",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique utilise-t-il un hébergement ayant une démarche de réduction de son empreinte environnementale ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service ne repose pas sur l’activité d’un centre de données",
  "moyenTest": "Vérifier ou demander des engagements à l’hébergeur pour diminuer son empreinte environnementale – a minima concernant les indicateurs suivants : émissions de GES (market-based et location-based), consommation en énergie, en eau, en ressources abiotiques (minérales/métalliques). S’assurer de la ratification du Code de conduite sur les centres de données par l’hébergeur et des actions associées.Documenter dans la déclaration d’écoconception du service l’empreinte environnementale de l’hébergement et la mise en place d’engagements environnementaux pour la minimiser.",
  "exempleDeclaration": "L’hébergement du service est assuré par [à compléter].Cet hébergeur est signataire du Code de Conduite sur les Datacentres.Il a par ailleurs pris les engagements suivant pour diminuer son empreinte environnementale : [à compléter][possibilité de renvoyer vers le site de l’hébergeur si nécessaire]"
 },
 {
  "id": "8.2",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique utilise-t-il un hébergement qui fournit une politique de gestion durable des équipements ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service n’utilise pas d’hébergement",
  "moyenTest": "Vérifier la mise en place d’un plan de gestion durable des équipements informatiques par l’hébergeur. Le plan devra couvrir des informations sur la durée de vie des équipements, la politique d’achat durable et les actions mises en place pour minimiser l’empreinte environnementale du cycle de vie du matériel utilisé par l’hébergeur. Pour valider le critère, ce plan devra être référencé dans la déclaration d’écoconception du service numérique.",
  "exempleDeclaration": "L’engagement écologique de l’hébergeur repose également sur une politique de gestion durable des équipements.[Possibilité de renvoyer directement à la politique de gestion des équipements de l’hébergeur]Afin de diminuer l’impact environnemental des équipements nécessaires à l’hébergement, les actions suivantes ont été entreprises :• Communication sur la durée de vie moyenne de son parc d’équipements : [à détailler]• Informations sur l’impact environnemental de l’achat de ces équipements : [à détailler]• Politique d’achat durable : [à détailler]• Actions pour optimiser la phase d’usage des équipements : [à détailler]• Actions pour optimiser la fin de vie des équipements (recyclage, réutilisation, reconditionnement) : [à détailler]"
 },
 {
  "id": "8.3",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique utilise-t-il un hébergement dont le PUE (Power Usage Effectiveness) est minimisé ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service n’utilise pas d’hébergement",
  "moyenTest": "Pour valider le critère, il faut choisir un hébergeur avec un PUE inférieur à 1,5 en réel (ou un PUE by design inférieur ou égal à 1,3 si les installations de l’hébergeur sont entrées en activité depuis moins de deux ans – en conséquence, le critère devra être réévalué passé ce délai de deux ans d’activité des installations –).Si possible, fournir un lien ou justificatif incluant le PUE de l'hébergement dans la déclaration d’écoconception du service.",
  "exempleDeclaration": "L’hébergement fournit les indicateurs suivants sur son efficacité énergétique :• PUE (Power Usage Effectiveness) réel [PUE by design si l’hébergement est activité depuis moins de 2 ans]: [à compléter]"
 },
 {
  "id": "8.4",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique utilise-t-il un hébergement dont son WUE (Water Usage Effectiveness) est minimisé ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service n’utilise pas d’hébergement",
  "moyenTest": "Le critère est validé si l’hébergeur du service numérique démontre une démarche de minimisation de sa consommation d’eau en suivant les indicateurs pertinents, en particulier son WUE. L’objectif d’un WUE inférieur ou égal à 0,4 L/kWh peut être visé (calculer en réel si possible et sinon, considérer le WUE by design, en particulier pour les centres de données qui sont en activité depuis moins de deux ans – le critère est donc à réévaluer passé ce délai de deux ans d’activité des installations –).La méthodologie de calcul et le type de WUE – réel ou by design – calculé sont précisés avec la valeur communiquée. Si possible, il faut fournir un lien ou justificatif incluant le WUE de l'hébergement dans la déclaration d’écoconception du service.",
  "exempleDeclaration": "L’hébergement fournit les indicateurs suivants sur son utilisation d’eau :• WUE (Water Usage Effectiveness) réel [WUE by design si l’hébergement est activité depuis moins de 2 ans]: [à compléter]"
 },
 {
  "id": "8.5",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique utilise-t-il un hébergement dont l’origine de consommation d’électricité est documentée et majoritairement d’origine renouvelable ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service n’utilise pas d’hébergement",
  "moyenTest": "Le critère est validé si l’hébergeur du service numérique est transparent sur son mix énergétique et documente une politique de recours majoritaire aux énergies renouvelables, ayant un impact effectif sur la réduction de la demande en énergie fossile. Au-delà de l’indicateur REF, l’hébergeur devra renseigner la quantité annuelle d’énergie contractualisée telle que décrite dans la section « Mise en œuvre » pour documenter sa politique de recours aux énergies renouvelables.La provenance de l’électricité consommée par l'hébergement sera documentée dans la déclaration d’écoconception du service, par exemple en renvoyant vers la documentation détaillée du fournisseur.",
  "exempleDeclaration": "Le mix énergétique de l’hébergement du service numérique est documenté et présente une consommation d’énergie renouvelable majoritaire comme l’attestent les données suivantes :• Quantité annuelle d’énergie contractualisée : [à compléter]         ◦ part de PPA sur le réseau français, mais hors site : [à compléter]         ◦ part autoconsommation (potentiellement par PPA ou support complet des coûts de capital et autres) : [à compléter]         ◦ part des garanties d’origines : [à compléter]• REF (Renewable Energy Factor) : [à compléter]• Part d’énergie part carbone : [à compléter]"
 },
 {
  "id": "8.6",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique utilise-t-il un hébergement dont la localisation géographique est cohérente avec ses activités et qui minimise son empreinte environnementale ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service n’utilise pas d’hébergement",
  "moyenTest": "Par valider ce critère, il conviendra de vérifier que l’hébergeur du service numérique est situé dans un pays où l’intensité carbone de la consommation électrique est minimale. Pour cela, vérifier que cette intensité est en dessous du seuil annuel de 100 gCO₂eq/kWh, en lien avec la trajectoire de réduction des émissions de gaz à effet de serre telle que définie par l’initiative Science-Based Targets (SBTi) et conformément aux objectifs de l’Accord de Paris (à partir de 2030, le seuil à respecter est de 80 gCO₂eq/kWh puis 0 gCO₂eq/kWh à partir de 2050). De façon complémentaire (pas nécessaire pour la validation de ce critère), favoriser le choix d’un hébergement dans le pays où la majorité de ses utilisateurs sont localisés.Documenter dans la déclaration d’écoconception, la localisation (pays, ville) de l’hébergement du service numérique.",
  "exempleDeclaration": "L’hébergement du service est situé dans les villes : [à compléter]L’intensité carbone du mix énergétique du pays où sont localisés l’hébergement est estimé à [à compléter] CO₂eq/kWh d’après [source].Il s’agit d’une valeur conforme à la trajectoire SBTi (Science-based Target Initiative) de réduction des émissions de gaz à effet de serre requise par l’accord de Paris.Il s’agit également du pays où la majorité des utilisateurs du service sont situés."
 },
 {
  "id": "8.7",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique utilise-t-il un hébergement qui traite efficacement la chaleur produite par les serveurs ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service n’utilise pas d’hébergement",
  "moyenTest": "Le critère est validé si l’hébergeur a mis en place des initiatives assurant la récupération et la réutilisation de la chaleur fatale générée par son installation, et que celles-ci sont documentées dans la déclaration d’écoconception du service numérique. Il est nécessaire que le bilan environnemental global de la réutilisation de la chaleur produite soit positif, en tenant compte de l’investissement initial pour la construction ou de l’adaptation des installations pour la validation du critère.De façon alternative, le critère peut être validé si le centre de données utilisé pour le service a un PUE inférieur à 1,3 en réel (ou un PUE by design inférieur ou égal à 1,2 si les installations de l’hébergeur sont entrées en activité depuis moins de deux ans – le critère est donc à réévaluer passé ce délai de deux ans d’activité des installations –). Un centre de données avec un PUE faible – bien qu’efficient énergétiquement – peut rendre impossible ou compliquée cette réutilisation de la chaleur fatale.",
  "exempleDeclaration": "[pas nécessaire si le PUE de l’hébergeur est inférieur ou égal à 1,2]L’hébergeur du service numérique a mis en place un système de récupération et de réutilisation de la chaleur fatale.Ce système permet de récupérer [à compléter] Wh en pleine capacité."
 },
 {
  "id": "8.8",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique héberge-t-il de façon distincte les données « chaudes » et « froides » ?",
  "priorite": "modere",
  "poids": 1.0,
  "applicabiliteDefaut": "N/A si le service numérique repose sur l’hébergement de moins de l’équivalent de 10 To de données",
  "moyenTest": "Pour valider ce critère, s'assurer que des stratégies de stockage appropriées sont mises en place pour les données froides, en prenant en compte leur empreinte environnementale.",
  "exempleDeclaration": ""
 },
 {
  "id": "8.9",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique duplique-t-il les données uniquement lorsque cela est nécessaire ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service n’utilise pas d’hébergement",
  "moyenTest": "Pour valider ce critère, vérifier la présence d’un SLA (Service Level Agreement) ajusté selon les besoins.",
  "exempleDeclaration": ""
 },
 {
  "id": "8.10",
  "themeNum": 8,
  "theme": "Hébergement",
  "libelle": "Le service numérique tient-il compte des contraintes externes pour minimiser l’impact environnemental des calculs et transferts de données asynchrones ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique n’inclut pas de calculs ou transferts de données asynchrones",
  "moyenTest": "Le service numérique justifie dans la déclaration d’écoconception de la mise en œuvre de méthodes pour décaler les calculs et transferts de données asynchrones en fonction de la disponibilité de l’énergie électrique (éviter les pics quotidiens de consommation électrique qui impliquent une électricité plus carbonée), de la charge des infrastructures internet, et éventuellement en fonction de la disponibilité des ressources de calcul quand cela est pertinent.",
  "exempleDeclaration": "Le service numérique [à compléter] décale les (sauvegarde, mises à jour, entraînement…) en fonction de la disponibilité de l’énergie électrique et de sa carbonation, de la charge du réseau internet et éventuellement en fonction de la disponibilité des ressources de calcul quand cela est pertinent. Plus en détails, les paramétrages suivants ont été mis en place :• Prise en compte des tensions sur l’approvisionnement énergétique : [à détailler]• Prise en compte de la disponibilité des ressources calculs : [à détailler]• Prise en compte des pics de sollicitation des réseaux : [à détailler]"
 },
 {
  "id": "9.1",
  "themeNum": 9,
  "theme": "Algorithmie",
  "libelle": "Le service numérique a-t-il interrogé la nécessité d’une phase d’entraînement pour éviter un usage non justifié et déraisonné ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "Applicable à tous les services",
  "moyenTest": "Justifier dans la déclaration d’écoconception le lien avec les fonctionnalités du service et les raisons expliquant la nécessité (si pertinent) de l’inclusion d’une phase d’entraînement dans le service numérique, en particulier en termes de valeur ajoutée pour l’utilisateur. Si les besoins sont clairement établis, il conviendra de définir un niveau de satisfaction suffisant et de choisir une fréquence d’entraînement proportionnée.Le critère est validé si le service n’intègre pas d’apprentissage non justifié et suit donc, dans l’éventualité de la mise en place d’une phase d’apprentissage, les critères de documentation susmentionnés démontrant l’utilité de la phase d’entraînement et son caractère proportionnel au regard de ses cibles ainsi que des fonctionnalités concernées.",
  "exempleDeclaration": "L’inclusion d’une phase d’entraînement pour le service numérique [à compléter] est justifiée par le besoin des cibles utilisatrices [à détailler].Ainsi, les fonctionnalités [à compléter] pour y répondre ne pouvaient être développées de façon optimale avec la recherche classique sans phase d’entraînementLes principaux gains pour les utilisateurs sont : [à compléter].En conséquence, la fréquence d’entraînement ne dépassera pas : [à compléter] tous les [à compléter] ans/mois."
 },
 {
  "id": "9.2",
  "themeNum": 9,
  "theme": "Algorithmie",
  "libelle": "Le service numérique utilise-t-il une phase d’apprentissage avec un niveau de complexité minimisé et proportionné à l’usage effectif du service ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique n'inclut pas de phase d’entraînement",
  "moyenTest": "Si le service ne repose pas sur des méthodes de régression ou autres méthodes peu coûteuses (low-complex, low-cost), justifier dans la déclaration d’écoconception du service le besoin de méthodes plus consommatrices par une référence à un état de l’art précisant la nécessité de méthodes plus complexes pour le cas d’usage cible.Le critère est validé si le choix de la méthode d’apprentissage est l’alternative la plus sobre disponible selon l’état de l’art et les caractéristiques du service, et que ces choix sont documentés dans la déclaration d’écoconception associée ainsi qu’auditables par un tiers.",
  "exempleDeclaration": "Un état de l’art a été réalisé pour choisir la méthode d’apprentissage la plus sobre dont voici les principaux contours publics [à compléter].En cohérence, la méthode d’entraînement choisie comprend les caractéristiques suivantes [à compléter].Il s’agit de la méthode la plus sobre disponible pour réponse au besoin actuel selon les connaissances et l’état de la recherche actuel."
 },
 {
  "id": "9.3",
  "themeNum": 9,
  "theme": "Algorithmie",
  "libelle": "Le service numérique a-t-il mis en place des mécanismes visant à limiter la quantité d’entraînement nécessaire à son fonctionnement ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique n'inclut pas de phase d’entraînement",
  "moyenTest": "Avant la conception du service, faire un état de l’art des modèles existants pouvant s’apparenter à la fonctionnalité visée. Utiliser un modèle pré-entraîné, si nécessaire en ajoutant des composants complémentaires (fine-tuning). Si le service n’utilise pas un modèle préexistant (déjà entraîné ou pré-entraîné), justifier dans la déclaration d’écoconception en quoi le cas d’usage est différent de ce qui existe dans l’état de l’art.Par ailleurs, pour valider le critère, le service devrait avoir mis en place le suivi d’indicateurs de consommation de ressources et de qualité des fonctions de la phase d’apprentissage pour assurer l’optimisation de la quantité d’entraînement sous-jacente au fonctionnement du service.",
  "exempleDeclaration": "Sur la base de l’état de l’art des modèles d’entraînement existant, le service numérique s’appuie sur un modèle pré-entraîné, ce qui œuvre à rationaliser la quantité de ressources nécessaires pour le fonctionnement du service / n’utilise pas un modèle préexistant (déjà entraîné ou pré-entraîné), en raison de [à justifier].Par ailleurs, les indicateurs suivants ont été mis en place pour adapter et jauger la quantité d’entraînement nécessaire aux réels besoins : [à lister]"
 },
 {
  "id": "9.4",
  "themeNum": 9,
  "theme": "Algorithmie",
  "libelle": "Le service numérique limite-il la quantité de données utilisées pour la phase d’apprentissage au strict nécessaire ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique n'inclut pas de phase d’entraînement",
  "moyenTest": "Utiliser des bases de données existantes pour l’entraînement de son service numérique. Vérifier que la collecte de données est minimisée et mentionner les méthodes mises en œuvre dans la déclaration d’écoconception du service numérique.Le critère est validé si le service utilise, dès que cela est possible, des bases de données existantes et applique les critères 7.1. et 7.2 pour la phase d’apprentissage tout en documentant sa gestion de données, et l’inclusion des enjeux de sobriété, dans sa déclaration d’écoconception.",
  "exempleDeclaration": "Le service numérique [à compléter] intègre les enjeux de sobriété pour la gestion des données nécessaire à la phase d’entraînementAinsi, les actions suivantes sont mises en place :• Utilisation de bases de données existantes : [à compléter]• Limitation de la captation de nouvelles données : [à compléter]• Système de mise en cache et de compression : [à compléter]"
 },
 {
  "id": "9.5",
  "themeNum": 9,
  "theme": "Algorithmie",
  "libelle": "Le service numérique optimise-t-il l’occurrence de mise à jour et de réentraînement des modèles en fonction de ses besoins et des cibles utilisatrices ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique n'inclut pas de phase d’entraînement",
  "moyenTest": "Fixer les conditions de déclenchement du réentraînement ou de la mise à jour des modèles algorithmiques du service en se basant sur les besoins réels des utilisateurs ou sur d’éventuelles contraintes légales. Minimiser la fréquence de ces opérations dans une démarche de sobriété. Documenter ces périmètres et les choix effectués dans la déclaration d’écoconception du service, en justifiant la prise en compte des principes d’écoconception.Le critère est validé s’il est démontré que la fréquence de réentraînement est proportionnelle aux besoins du service et des cibles utilisatrices et est, autant que possible, minimisée grâce au suivi d’indicateurs (de performance, de satisfaction et de consommation en ressources).",
  "exempleDeclaration": "Le service a défini les paramètres suivants de déclenchement des mises à jour des modèles algorithmiques : [à compléter].Des indicateurs de suivi ont été mis en place pour ajuster ces fréquences : [à compléter].Il s’agit de l’option la plus frugale puisque : [à détailler]."
 },
 {
  "id": "9.6",
  "themeNum": 9,
  "theme": "Algorithmie",
  "libelle": "Le service numérique utilise-t-il des techniques de compression pour les modèles utilisés lors de la phase d’entraînement ?",
  "priorite": "recommande",
  "poids": 1.25,
  "applicabiliteDefaut": "N/A si le service numérique n'inclut pas de phase d’entraînement",
  "moyenTest": "Le critère est validé si le service numérique justifie de la mise en œuvre de méthodes de compression de modèles, en indiquant les gains réalisés dans la déclaration d’écoconception du service numérique.",
  "exempleDeclaration": "Les modèles utilisés pour l’entraînement sous-jacent au service numérique s’appuie sur les méthodes de compression suivantes : [à compléter].Ceux-ci permettent des gains d’efficacité en termes de : [à détailler]."
 },
 {
  "id": "9.7",
  "themeNum": 9,
  "theme": "Algorithmie",
  "libelle": "Le service numérique utilise-t-il une stratégie d’inférence optimisée en termes de consommation de ressources et des cibles utilisatrices ?",
  "priorite": "prioritaire",
  "poids": 1.5,
  "applicabiliteDefaut": "N/A si le service numérique n'inclut pas de phase d’inférence",
  "moyenTest": "La stratégie d’inférence du service est adaptée aux cibles utilisatrices en minimisant les ressources nécessaires à son fonctionnement et les requêtes inutiles. Des indicateurs de suivi de consommation en ressources et de satisfaction des utilisateurs sont mis en place pour ajuster la phase d’inférence, avec pour objectif la frugalité du modèle sous-jacent au service.Le critère est validé si le service numérique démontre dans sa déclaration d’écoconception la mise en place de principes d’écoconception dans sa phase d’inférence, adaptée aux besoins des utilisateurs.",
  "exempleDeclaration": "La phase d’inférence du service numérique est adaptée aux cibles utilisatrices, comme le montre les éléments suivants : [à compléter].Des indicateurs de satisfaction sont mis en place : [à détailler].La consommation de ressources représenterait : [à détailler].Ces valeurs seront minimisées pour atteindre [à compléter].Les actions suivantes ont été mises en place pour atteindre cet objectif : [à détailler]."
 }
];
